Arithmetic with R

```{r}
5+5-3
10-2
3*5
(5+5)/2
27%%2
```

Variable assigment

```{r}
x <- 10
x

y <- 9

x+y

result <- x-y
result
```


Basics data types in R

```{r}
my_numeric <-423
my_character <- "universe"
my_logical <- FALSE

class(my_numeric)
class(my_character)
class(my_logical)
```

create a vector 

```{r}
numeric_vector <- c(1,10,49)
numeric_vector

character_vector <- c("a","b","c")

boolean_vector <- c(TRUE,FALSE,TRUE)

character_vector
boolean_vector



poker_vector <- c(140,-50,-20,-120, 100)
roulette_vector <- c(-24,-50,10,350,10)


poker_vector



```

naming a vector

```{r}
names(poker_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

poker_vector

names(roulette_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

roulette_vector

```

Selection by comparision


```{r}
age <- 21

age >= 18


selection_vector <- poker_vector > 0
selection_vector


poker_winning_days <- poker_vector[selection_vector]
poker_winning_days

```
Calculating

```{r}
x_vector <- c(4,7,9)
y_vector <- c(12,45,78)

result_vector <- x_vector+y_vector
result_vector
```


vector selection

```{r}
poker_vector
poker_vector[3]
poker_vector[c(2,3,4)]
poker_vector[2:5]
```

MATRICES

```{r}
matrix(1:9, byrow=TRUE, nrow=3)
```
Analyze matrices

```{r}
new_hope <- c(460.988,314.4)
empire_strikes <- c(290.475,247.900)
return_jedi <- c(309.306,165.8)

box_office <- c(new_hope, empire_strikes, return_jedi)
box_office


star_wars_matrix <- matrix(box_office, byrow=TRUE, nrow=3)
star_wars_matrix

```
```{r}
region <- c("US", "non-US")
titles <- c("A new hope","The empire strikes back", "Return of the Jedi")

colnames(star_wars_matrix) <- region
rownames(star_wars_matrix) <- titles
star_wars_matrix
```
rowSums

```{r}
rowSums(star_wars_matrix)
colSums(star_wars_matrix)
```
cbind and rbind

```{r}
total_revenue_by_title <- rowSums(star_wars_matrix)
total_revenue_by_region <- colSums(star_wars_matrix)

total <- cbind(star_wars_matrix, total_revenue_by_title)
total <- rbind(total, total_revenue_by_region)
total
```
Selection of matrix elements

```{r}
star_wars_matrix

star_wars_matrix[1,2]
star_wars_matrix[1:2,2]

star_wars_matrix[c(1,3),1]
star_wars_matrix[c(1,3),]
star_wars_matrix[,c(1,2)]
```
Arithmetic with matrices

```{r}
mean <- star_wars_matrix/5
mean *2
```
Factor

```{r}
sex_vector <- c("Male", "Female", "Female", "Male", "Male")
factor_sex_vector <- factor(sex_vector)
factor_sex_vector
```
```{r}
temperature_vector <- c("High", "Low", "High", "Low", "Medium")
factor_temperature_vector <- factor(temperature_vector, order=TRUE, levels=c("Low","Medium","High"))
factor_temperature_vector
```
Factor levels

```{r}
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
factor_survey_vector
levels(factor_survey_vector) <- c("Female", "Male")

```

Summary

```{r}
summary(factor_survey_vector)
```

Ordered factors
```{r}
male <- factor_survey_vector[1]
female <- factor_survey_vector[2]

male>female

speed_vector <- c("medium","slow", "slow", "medium", "fast")
factor_speed_vector <- factor(speed_vector)
factor_speed_vector
factor_speed_vector <- factor(speed_vector, ordered=TRUE, levels=c("slow", "medium", "fast"))


speed_1 <- factor_speed_vector[2]
speed_5 <- factor_speed_vector[5]
speed_1>speed_5
speed_5>speed_1
```


